# Generated by Django 3.2.4 on 2021-06-22 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_weather_api', '0002_weatherforecastday_average_temp_c'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherforecastday',
            name='created_at',
        ),
    ]
